# Generated by Django 6.0.2 on 2026-02-06 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='bill_payment_status',
            field=models.BooleanField(choices=[(True, 'Paid'), (False, 'Unpaid')], default=False),
        ),
        migrations.AlterField(
            model_name='billing',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.booking'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.customer'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.order'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.staff'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.table'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
    ]
